### ISSUE TITLE
Some states missing hospital information; (NJ, GA missing HOSP_NPI)

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-dbt#25]
To track which facility/hosptial the encounter/discharge was at we can use `HOSP_NPI` but this is not available in some states in including  GA and NJ. 

**on-hold until v0.3. For v0.2, hospital level metrics will be calculate  based on encoutners/discharges with available `HOSP_NPI`**

##  Action Items
- [x] Figure out how to label encounter hospital/lcoaiton for our hospital level mart items.

**Comment by her43** [comment]
the variable [hospid](https://hcup-us.ahrq.gov/db/vars/siddistnote.jsp?var=hospid) seems to be more widely available than the other variable. Add to database instead?

**Comment by alinasmahl1** [comment]
let's add both

**Comment by ran-codes** [comment]
- [ ] currently `AZ_SID_2016_CORE` is missing HOSPID.. to track down issue

**Comment by ran-codes** [comment]
HOSPID was added. pending production run be closing.

**Comment by ran-codes** [comment]
@her43 production run done. Feel free to close issue after you've checked over the results.

**Comment by alinasmahl1** [comment]
@her43 I'm not sure where this past bug is, but we need a variable for state and year. That's just hard coded each for each state and year. The HCUP State and Year variables (AYEAR, PSTATE) are dependent on when the data is from, so for example there could be data in the NY 2020 SID that's from NJ 2019. We need to be able to filter that data out, but currently there isn't a way to do that when we pull in multiple states and years at the same time

**Comment by alinasmahl1** [comment]
hard code issue moved to another issue. This closed
