### ISSUE TITLE
[v0.3 seeds]

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-dbt#26]
Need a few more seed tables

- [ ]  add  2009 or 2010 NY  SID or SEDD. These we in the original HCUP folder which have been copied to raw/_upload_2023-04-17/
- [ ] place level indicators

## Action Items

-  #29

**Comment by alinasmahl1** [comment]
@ran-codes also realizing in all teh intermediate files we need to have a var indicating what state and year the data is from.

**Comment by ran-codes** [comment]
got it. we have two fields in all base tables ('db' and 'file') that store this information. Created #27 to track the inclusion fo these fields in all intermediate tables.

**Comment by alinasmahl1** [comment]
Great- we'll want in marts too I'd think... so that would make it a grouping var for those final marts

**Comment by ran-codes** [comment]
got it. updated #27 !

**Comment by alinasmahl1** [comment]
let's include state fips as well.

**Comment by alinasmahl1** [comment]
need to include RACE_X as well

**Comment by alinasmahl1** [comment]
andd another one-- need to incldue PSTATE- this is the state that the observation/encounter is from (we could extract from PSTCO, but cleaner to just include this)

**Comment by alinasmahl1** [comment]
@ran-codes please see above - can we add PSTATE -  example: if w're lookign at the NY 2017 SID

 and someone was living in jersey, but hopsitalized in NY- PSTATEE would be = NJ
so we want PSTATE in addition to SID state
 becuase we don't actually want to include people who lived in jersey in some of these analysis

**Comment by alinasmahl1** [comment]
@ran-codes in looking through the data i'm seeing that for some reason the georgia data doesn't have ICD 10 admitting (I10_DX_admitting) codes incldued-- i'm guessing there's a bug in one of the data cleaning/selection steps?
