### ISSUE TITLE
Georgia missing ICD 10 Admitting code

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-dbt#29]
in looking through the data i'm seeing that for some reason the georgia data doesn't have ICD 10 admitting (I10_DX_admitting) codes incldued-- i'm guessing there's a bug in one of the data cleaning/selection steps?

**Comment by her43** [comment]
According to the documentation, Georgia is missing the variable [I10_DX_Visit_Reasonn](https://hcup-us.ahrq.gov/db/vars/sedddistnote.jsp?var=i10_dx_visit_reasonn)

**Comment by her43** [comment]
[i10_dx_admitting ](https://hcup-us.ahrq.gov/db/vars/siddistnote.jsp?var=i10_dx_admitting) might be a SID only variable

**Comment by her43** [comment]
[SID documentation](https://hcup-us.ahrq.gov/db/state/siddist/siddistvarnote2018.jsp) - GA is missing the variable

**Comment by her43** [comment]
[i10_dxn](https://hcup-us.ahrq.gov/db/vars/siddistnote.jsp?var=i10_dxn) exists for all states in both SID and SEDD data sets, might be an alternative.

**Comment by her43** [comment]
per @alinasmahl1 let's pull in i10_dxn - i10_dx1 and i10_dx2 at least. Some debate whether 3 and 4 are useful.

**Comment by ran-codes** [comment]
Already have i10_dx1 and i10_dx2 in all models. Flu recoding utilizes dx1 and dx2. So no need ot change anything.
