### ISSUE TITLE
add pstate and Race_x to marts

### ISSUE THREAD

**Issue by alinasmahl1** [Drexel-UHC/hcup-dbt#32]
added ptate and RAce_x to int now need to add to downstream

## Action Items

- [x] PSTATEA and RACE_X added as base model columns
- [x] Add to int__sid_core
- [x] production run + documentation refresh
- [x] Add to int__sedd_core @her43 during 1:1
- [x] production run + documentation refresh

**Comment by ran-codes** [comment]
## Action Items

- [ ] PSTATEA and RACE_X added as base model columns
- [ ] Add to int__sid_core
- [ ] Add to int__sedd_core @her43 during 1:1

**Comment by ran-codes** [comment]
@her43 production run done. Feel free to close the issue after you've checked over the results.

**Comment by alinasmahl1** [comment]
@her43 @ran-codes doing some analysis and realized that we may want to include additional diagnosis codes-- can we please add in I10_DX3 to I10_DX10  for the int models?

**Comment by ran-codes** [comment]
@her43 take a first stab?

**Comment by her43** [comment]
> @her43 @ran-codes doing some analysis and realized that we may want to include additional diagnosis codes-- can we please add in I10_DX3 to I10_DX10 for the int models?

I wondered If we'd ever go back and add those. I'll add the ICD9 equivalent variables too.

**Comment by her43** [comment]
This issue is complete. All variables we've discussed so far have been added. Let's open a new issue for any other changes that need to be made in the future.
