### ISSUE TITLE
move the base modeling automation from ETL repo to DBT repo

### ISSUE THREAD

**Issue by alinasmahl1** [Drexel-UHC/hcup-dbt#33]
currently base modeling in in ETL, but better for it to sit in DBT

**Comment by ran-codes** [comment]
## Action Items

- [ ] migrate DBT specific ETL to DBT repo
- [ ] Cull migrated code from ETL repo
- [ ] Cull unused ETL code from DBT repo

**Comment by ran-codes** [comment]
done. all dbt specific ETL mirgrated to DBT rpeository
