### ISSUE TITLE
BCHC team data request: -  hcup: city level hostpitaliaztion of opioid and gun related, asthma.

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-dbt#35]
btw saima mentioned bCHC is interest in if HCUP can provide city level hospitalizations ata in related to: hostpitaliaztion of opioid and gun related, asthma.

**Comment by alinasmahl1** [comment]
@ran-codes I just saw this- missed this before (I dont' think it alerts me unless i'm tagged). 

I think we'd need a new data request for this-- I don't think making this data available would necessarily be allowed under our current DUA.

**Comment by ran-codes** [comment]
@alinasmahl1 thanks for the clarification and apologies for not tagging. 


@SaimaNiamat here's a late reply. (Better late than never 😄 ). Going to close this for now as it seems not a very easy thing ...

**Comment by SaimaNiamat** [comment]
@ran-codes thanks for getting back!
