### ISSUE TITLE
new NY data

### ISSUE THREAD

**Issue by her43** [Drexel-UHC/hcup-dbt#36]
Continuing NY data (plus some data for some other states)

See: [Adding new SID data](https://github.com/Drexel-UHC/hcup-etl/issues/29)

Continuing where we left off in [ETL New York data Sep 2023](https://github.com/Drexel-UHC/hcup-etl/issues/31)

See [Protocol for modifying base models](https://github.com/Drexel-UHC/hcup-dbt/discussions/34) as a guideline for what we're doing now.

**Comment by her43** [comment]
I'm in .etl/index.R

step 0 setup went fine.

in section 1. Pre-DBT ETL

This went fine:

```
## Models > Source 
  etl$file_ids %>% walk(~generate_source_yml(.x, env = "uhc",etl))
   
```

Running this:
```
## Models > Base > SID 
  generate_dbt_base_metadata('SID', etl) %>% 
    group_by(row_number()) %>% 
    group_walk(~write_dbt_base_model(.x, etl))
```

I got an error:
```
→ Start base__model.sql for GA_SID_2019_CHGS
✔ base__ga_sid_2019_chgs.sql written
→ Start base__model.sql for GA_SID_2019_CORE
✔ base__ga_sid_2019_core.sql written
→ Start base__model.sql for MN_SID_2016_CHGS
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '../../hcup-dbt/models/base/SID/MN/base__mn_sid_2016_chgs.sql': No such file or directory
```

I Checked the SID folder, and only some of the states/years "base__..." files are there. I feel like I'm missing a step here? I thought that this step was supposed to create these .sql files? But the error says it doesn't exist... which means it should *already* exist? I checked and there is corresponding parquet and yml files for mn_sid_2016_chgs, just like all the other states/years I've completed ETL for. So I don't really know why this one would cause a specific problem, unless I missed a step.

**Comment by her43** [comment]
Only thing I can think of is that maybe I need to create new empty folders for the other states? There are only 4 folders for AZ, GA, NJ, NY in the ".../models/base/SID/" folder. Maybe it's trying to write the files for MN but can't because the subfolder it wants to write to doesn't exist. 

Thoughts, @ran-codes ?

**Comment by her43** [comment]
> Only thing I can think of is that maybe I need to create new empty folders for the other states? There are only 4 folders for AZ, GA, NJ, NY in the ".../models/base/SID/" folder. Maybe it's trying to write the files for MN but can't because the subfolder it wants to write to doesn't exist.
> 
> Thoughts, @ran-codes ?

Actually, that seemed to fix the issue completely. I need to write in some code to create the state-specific subfolder if it doesn't already exist yet.

**Comment by her43** [comment]
> FYI in case it's useful: https://stackoverflow.com/questions/4216753/folder-management-with-r-check-existence-of-directory-and-create-it-if-it-does (so you can do this as part of the code; create if it doesnt exist, dont create otherwise)

this is actually the one I used as reference! haha

**Comment by her43** [comment]
Finished with step 1 in R.

moving on to DBT in visual studio.

When I ran `dbt compile`, part of the output contained this warning:

```
18:25:34  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.hcup.example
```

I don't know if this is important, @ran-codes ? Do I need to do something about this in the sense that it will cause me issues if I don't do something? or can I ignore this warning? We can look at this together in our meeting.

**Comment by her43** [comment]
Was able to run "dbt run" in visual studio, mostly. I was able to run all the base models. Had a few errors due to memory size. Turns out, I have 32 gb memory on my UHC desktop (I think I have the same amount of memory as @alinasmahl1's computer?) and it still wasn't enough.

- [ ] Next Step: attempt to run on a different computer.

Runtime Error in model int__sid_core (models\intermediate\int__sid_core.sql)
Out of Memory Error: could not allocate block of 262144 bytes (26843317686/26843545600 used)

To run this model alone, run:
`dbt run --models int__sid_core`

And other marts that are based on this would still need to be run.

**Comment by ran-codes** [comment]
1. int__side core is hte biggest one. (merges all base models) everthing downstream is very small compared to it as they just aggregate rows from it. 
2. run on 64gb computer. Usama's worked for me. 

**Suggest running no a 64 GB computer.**

> worst case scenario we'll deploy to azure db such as azure databricks (but this is going to cost some $$$). But BigQuery would be cheaper than Azure as its serverless and already well supported by DBT... but that's another discussion.

**Comment by usamabilal** [comment]
what do i need to do?

**Comment by alinasmahl1** [comment]
my computer has 64 gb, so Heather is going to give that a try tomorrow. 
Let's avoid doing the big bucks approach until we've exhausted other options. Because needing to do the $$ option means we may need to rethink some of our approach... (if it's really expensive)

**Comment by ran-codes** [comment]
Agreed to avoid big bucks. @her43, im here to support if the 64gb run doesn't work ( to help debug or optimize SQL models for performance).

**Comment by her43** [comment]
@ran-codes I've been following your instructions from [here](https://drexel-uhc.github.io/analytics-corner/pages/manuals/dbt/get-started-install.html) to get everything set up on @alinasmahl1 's computer and I've run into my first issue.

I got to the end of part 1 local setup, to the "Check that DBT can compile models" phase. I cannot compile.

```
(.venv) PS C:\Users\her43\Documents\GitHub\hcup-dbt> .\.venv\Scripts\activate
(.venv) PS C:\Users\her43\Documents\GitHub\hcup-dbt> python --version
Python 3.10.11
(.venv) PS C:\Users\her43\Documents\GitHub\hcup-dbt> dbt compile
14:23:45  Encountered an error while reading the project:
14:23:45    ERROR: Runtime Error
  Could not find profile named 'hcup'
14:23:45  Encountered an error:
Runtime Error
  Could not run dbt
```

In the console, under "Problems" there is a problem for dbt_project.yml:
```
An error occured while initializing the dbt project, probably the Python interpreter is not correctly setup: Runtime Error
  Could not find profile named 'hcup'
```

Here is what I think it's talking about in dbt_project.yml:
lines 9 and 10:
```
# This setting configures which "profile" dbt uses for this project.
profile: 'hcup'
```

**Comment by ran-codes** [comment]
# profiles.yml

Do you ahve a profiles.yml. This is a non-git file that contains project settings that change with the user. (e.g. what environment dev vs prod).  

![image](https://github.com/Drexel-UHC/hcup-dbt/assets/45013044/1aceb529-c7de-4bbd-baab-b1a33596aba0)


If you don't just copy over the one on your comptuer.

**Comment by her43** [comment]
that did help, thanks!

**Comment by ran-codes** [comment]
@her43 we should update documentation on the analytics corner to reflect this. That repo was  a self contained example... we should add a warning at that section (e.g. if you re using this as a ref for your own project... please check you have profiles.yml... etc).


As you use more DBT and get a better grasp of things. itt would be helpful for me/you/others for you to be able to update that UHC documentation yourself. Lmk if that's something you are interested in @her43. Its all built in R with Quarto.

**Comment by her43** [comment]
did production run dbt, still had an error:

```
15:29:15  135 of 146 START sql external model parquet.int__sid_core ...................... [RUN]
15:29:37  135 of 146 ERROR creating sql external model parquet.int__sid_core ............. [ERROR in 22.03s]
```


```
15:31:07  141 of 146 SKIP relation parquet.int__flu_ip ................................... [SKIP]
15:31:07  142 of 146 SKIP relation parquet.int__flu_ip_zcta .............................. [SKIP]
15:31:07  143 of 146 SKIP relation parquet.mart__flu_ip_hospital_pay ..................... [SKIP]
15:31:07  144 of 146 SKIP relation parquet.mart__flu_ip_rh_hospital ...................... [SKIP]
15:31:07  145 of 146 SKIP relation parquet.mart__flu_ip_urban_rh ......................... [SKIP]
15:31:07  146 of 146 SKIP relation parquet.mart__flu_ip_cost_city ........................ [SKIP]
```


```
15:31:08  Completed with 1 error and 0 warnings:
15:31:08
15:31:08  Runtime Error in model int__sid_core (models\intermediate\int__sid_core.sql)
15:31:08    Out of Memory Error: could not allocate block of 262144 bytes (13421584733/13421772800 used)
15:31:08
15:31:08  Done. PASS=139 WARN=0 ERROR=1 SKIP=6 TOTAL=146
```

**Comment by ran-codes** [comment]
@her43 thanks for adding new years. I pushed a SQL optimization (see #38)  for our intermediate models and it should run now. Give it another shot?

**Comment by her43** [comment]
Everything discussed in this issue so far has been solved & completed. Closing this issue.
